// Code generated by protoc-gen-microweb. DO NOT EDIT.
// source: proto.proto

package proto

import (
	"bytes"
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-chi/render"
	"github.com/golang/protobuf/jsonpb"
)

type webJupyterNotebookSupportHandler struct {
	r chi.Router
	h JupyterNotebookSupportHandler
}

func (h *webJupyterNotebookSupportHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.r.ServeHTTP(w, r)
}

func (h *webJupyterNotebookSupportHandler) GenerateHTML(w http.ResponseWriter, r *http.Request) {

	req := &JupyterNotebookJSON{}

	resp := &JupyterNotebookHTML{}

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusPreconditionFailed)
		return
	}

	if err := h.h.GenerateHTML(
		r.Context(),
		req,
		resp,
	); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	render.Status(r, http.StatusCreated)
	render.JSON(w, r, resp)
}

func RegisterJupyterNotebookSupportWeb(r chi.Router, i JupyterNotebookSupportHandler, middlewares ...func(http.Handler) http.Handler) {
	handler := &webJupyterNotebookSupportHandler{
		r: r,
		h: i,
	}

	r.MethodFunc("POST", "/api/v0/convert", handler.GenerateHTML)
}

// JupyterNotebookJSONJSONMarshaler describes the default jsonpb.Marshaler used by all
// instances of JupyterNotebookJSON. This struct is safe to replace or modify but
// should not be done so concurrently.
var JupyterNotebookJSONJSONMarshaler = new(jsonpb.Marshaler)

// MarshalJSON satisfies the encoding/json Marshaler interface. This method
// uses the more correct jsonpb package to correctly marshal the message.
func (m *JupyterNotebookJSON) MarshalJSON() ([]byte, error) {
	if m == nil {
		return json.Marshal(nil)
	}

	buf := &bytes.Buffer{}

	if err := JupyterNotebookJSONJSONMarshaler.Marshal(buf, m); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

var _ json.Marshaler = (*JupyterNotebookJSON)(nil)

// JupyterNotebookJSONJSONUnmarshaler describes the default jsonpb.Unmarshaler used by all
// instances of JupyterNotebookJSON. This struct is safe to replace or modify but
// should not be done so concurrently.
var JupyterNotebookJSONJSONUnmarshaler = new(jsonpb.Unmarshaler)

// UnmarshalJSON satisfies the encoding/json Unmarshaler interface. This method
// uses the more correct jsonpb package to correctly unmarshal the message.
func (m *JupyterNotebookJSON) UnmarshalJSON(b []byte) error {
	return JupyterNotebookJSONJSONUnmarshaler.Unmarshal(bytes.NewReader(b), m)
}

var _ json.Unmarshaler = (*JupyterNotebookJSON)(nil)

// JupyterNotebookHTMLJSONMarshaler describes the default jsonpb.Marshaler used by all
// instances of JupyterNotebookHTML. This struct is safe to replace or modify but
// should not be done so concurrently.
var JupyterNotebookHTMLJSONMarshaler = new(jsonpb.Marshaler)

// MarshalJSON satisfies the encoding/json Marshaler interface. This method
// uses the more correct jsonpb package to correctly marshal the message.
func (m *JupyterNotebookHTML) MarshalJSON() ([]byte, error) {
	if m == nil {
		return json.Marshal(nil)
	}

	buf := &bytes.Buffer{}

	if err := JupyterNotebookHTMLJSONMarshaler.Marshal(buf, m); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

var _ json.Marshaler = (*JupyterNotebookHTML)(nil)

// JupyterNotebookHTMLJSONUnmarshaler describes the default jsonpb.Unmarshaler used by all
// instances of JupyterNotebookHTML. This struct is safe to replace or modify but
// should not be done so concurrently.
var JupyterNotebookHTMLJSONUnmarshaler = new(jsonpb.Unmarshaler)

// UnmarshalJSON satisfies the encoding/json Unmarshaler interface. This method
// uses the more correct jsonpb package to correctly unmarshal the message.
func (m *JupyterNotebookHTML) UnmarshalJSON(b []byte) error {
	return JupyterNotebookHTMLJSONUnmarshaler.Unmarshal(bytes.NewReader(b), m)
}

var _ json.Unmarshaler = (*JupyterNotebookHTML)(nil)
