FROM amd64/alpine:latest

RUN apk update && \
	apk upgrade && \
	apk add ca-certificates mailcap && \
	rm -rf /var/cache/apk/* && \
	echo 'hosts: files dns' >| /etc/nsswitch.conf

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.label-schema.name="OCIS JUPYTER" \
  org.label-schema.vendor="ownCloud GmbH" \
  org.label-schema.schema-version="1.0"

EXPOSE 9105 9106 9109

ENTRYPOINT ["/usr/bin/ocis-jupyter"]
CMD ["server"]

COPY bin/ocis-jupyter /usr/bin/ocis-jupyter
